### ISSUE TITLE
Remove `_token` argument from TokenHolder::setup function

### ISSUE THREAD

**Issue by pgev** [OpenST/openst-contracts#187]
Currently, TokenHolder::setup (as TokenHolder acts as a master copy, this function "replaces" constructor) signature is:

```solidity
    function setup(
        EIP20TokenInterface _token,
        address _tokenRules,
        address _owner,
        address[] calldata _sessionKeys,
        uint256[] calldata _sessionKeysSpendingLimits,
        uint256[] calldata _sessionKeysExpirationHeights
    )
```

However,  `_token` argument could and should be retrieved from `_tokenRules`.

Hence, new signature should be:
```solidity
    function setup(
        address _tokenRules,
        address _owner,
        address[] calldata _sessionKeys,
        uint256[] calldata _sessionKeysSpendingLimits,
        uint256[] calldata _sessionKeysExpirationHeights
    )
```

**Comment by benjaminbollen** [comment]
this changes the ABI; and I think this is not important enough by itself to update it.  However, this comment and other improvements *should* be collected and presented together in an OIP so that in a future release these can be taken together in a single interface change.

Closing this for now; @pgev writing an OIP for now is too much work perhaps.  Can you open a tracking ticket for defensible interface changes in openst-contracts and already reference this (closed) issue?
