### ISSUE TITLE
Move economy wide constants to UserWalletFactory::constructor

### ISSUE THREAD

**Issue by pgev** [OpenST/openst-contracts#188]
Currently, UserWalletFactory::createUserWallet() function signature is:

```solidity
    function createUserWallet(
        address _gnosisSafeMasterCopy,
        bytes calldata _gnosisSafeData,
        address _tokenHolderMasterCopy,
        address _token,
        address _tokenRules,
        address[] calldata _sessionKeys,
        uint256[] calldata _sessionKeysSpendingLimits,
        uint256[] calldata _sessionKeysExpirationHeights
    )
```

To improve consistency (all users of the economy are created with the same inputs) and gas consumption (should be checked, however, taking into consideration that SLOAD takes 200 gas, it should improve) the economy wide constants should be moved into UserWalletFactory constructor (constructor does not exist currently).

Here is the UserWalletFactory::constructor() signature:

```solidity
    constructor(
        address _gnosisSafeMasterCopy,
        address _tokenHolderMasterCopy,
        address _token,
        address _tokenRules,
    )
```

Here is the UserWalletFactory::createUserWallet() function signature:

```solidity
    function createUserWallet(
        bytes calldata _gnosisSafeData,
        address[] calldata _sessionKeys,
        uint256[] calldata _sessionKeysSpendingLimits,
        uint256[] calldata _sessionKeysExpirationHeights
    )
```

**Comment by benjaminbollen** [comment]
this changes the ABI; and I think this is not important enough by itself to update it.  However, this comment and other improvements *should* be collected and presented together in an OIP so that in a future release these can be taken together in a single interface change.

Closing this for now; @pgev writing an OIP for now is too much work perhaps.  Can you open a tracking ticket for defensible interface changes in openst-contracts and already reference this (closed) issue?
